[global]
pid = /var/run/php-fpm.pid
error_log = /var/log/php-fpm.log
log_level = error
emergency_restart_threshold = 3
emergency_restart_interval = 1m
process_control_timeout = 5s

[www]
user = laravel
group = laravel
listen = 127.0.0.1:9000
listen.backlog = 128
listen.allowed_clients = 127.0.0.1

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500

php_admin_value[error_log] = /var/log/php-fpm-www.log
php_admin_flag[log_errors] = on

catch_workers_output = yes
decorate_workers_output = no 